name: curve25519 Rust

on:
  push:
    branches: [ '**' ]
    paths:
      - 'curve25519-dalek/**'
      - '.github/workflows/curve25519-dalek.yml'
  pull_request:
    branches: [ '**' ]
    paths:
      - 'curve25519-dalek/**'
      - '.github/workflows/curve25519-dalek.yml'

defaults:
  run:
    working-directory: curve25519-dalek

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: '-D warnings'

jobs:

  verus:
    name: Run `cargo verify verus`
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@1.88.0
    - name: Install Verus
      run: |
        wget https://github.com/verus-lang/verus/releases/download/release%2F0.2025.08.01.33c6cec/verus-0.2025.08.01.33c6cec-x86-linux.zip
        unzip verus-0.2025.08.01.33c6cec-x86-linux.zip
        mv verus-x86-linux ~/.cargo/bin
        cd ~/.cargo/bin
        ln -s verus-x86-linux/cargo-verus
    - name: Run test
      run: | 
        cargo-verus verify -- --smt-option smt.random_seed=0

